In [4]:
import numpy as np
rows = 5
pas_tri = np.zeros([rows, rows], dtype = int)
pas_tri[0, 0] = 1
pas_tri[1, 0] = 1
pas_tri[1, 1] = 1
for i in range(2, rows):
    for j in range(0, i + 1):
        pas_tri[i, j] = pas_tri[i - 1, j - 1] + pas_tri[i - 1, j]
print(pas_tri)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]
