In [21]:
import numpy as np
n = int(input('Number of Rows: '))
pas = np.empty([n, n], dtype = int)
pascal[0, 0] = 1
pascal[1, 0] = 1
pascal[1, 1] = 1
for i in range(2, n):
    for j in range(0, i + 1):
        pascal[i, j] = pascal[i - 1, j - 1] + pascal[i - 1, j]
print(pascal)

Number of Rows:  5


[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]
